name: flutter_application_test
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# SDK environment version
environment:
  sdk: '>=3.0.0 <4.0.0' # Correction des caractères HTML '&gt;' et '&lt;'

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  http: ^1.1.2
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.0.0 # Vérifie si une version plus récente existe si tu as des problèmes
  timezone: ^0.9.2
  firebase_app_check: ^0.2.2 # Vérifie si une version plus récente existe si tu as des problèmes

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  pigeon: ^18.0.0 

# Flutter configuration
flutter:
  uses-material-design: true

  # Pour inclure des assets dans ton application, ajoute une section assets comme ceci :
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Pour ajouter des polices personnalisées à ton application, ajoute une section fonts ici,
  # dans cette section "flutter". Chaque entrée de cette liste doit avoir une
  # clé "family" avec le nom de la famille de polices, et une clé "fonts" avec une
  # liste contenant la ressource de police et d'autres descripteurs. Par exemple :
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Pour plus de détails sur les polices provenant de packages,
  # voir https://flutter.dev/custom-fonts/#from-packages
