name: flutter_application_test
description: "A new Flutter project implementing Trello-like features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  # firebase_app_check: ^0.2.1+16 # Gardé car c'est du code commenté, pas une explication

  provider: ^6.1.1

  flutter_dotenv: ^5.1.0

  intl: ^0.19.0

  cloud_firestore: ^4.15.4

  http: ^1.2.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
