name: flutter_application_test
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# SDK environment version
environment:
  sdk: '>=3.0.0 <4.0.0'

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  http: ^1.1.2
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.0.0
  timezone: ^0.9.2

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# Flutter configuration
flutter:
  uses-material-design: true
