// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwLG3EDrSg9y-oSLzuWK-K5Ae2zfSf-Gc',
    appId: '1:455848600257:web:c3dfb67e8656e08b676a40',
    messagingSenderId: '455848600257',
    projectId: 'applicationtestflutter',
    authDomain: 'applicationtestflutter.firebaseapp.com',
    storageBucket: 'applicationtestflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOhuZrxhxAylijL8TynqFSqqALLKRjios',
    appId: '1:455848600257:android:2402c55bf2bd72ef676a40',
    messagingSenderId: '455848600257',
    projectId: 'applicationtestflutter',
    storageBucket: 'applicationtestflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdGfWPEaRQK9KIRrgfTpxGH_Vqtikq18Q',
    appId: '1:455848600257:ios:aa20ae20d5443b70676a40',
    messagingSenderId: '455848600257',
    projectId: 'applicationtestflutter',
    storageBucket: 'applicationtestflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdGfWPEaRQK9KIRrgfTpxGH_Vqtikq18Q',
    appId: '1:455848600257:ios:aa20ae20d5443b70676a40',
    messagingSenderId: '455848600257',
    projectId: 'applicationtestflutter',
    storageBucket: 'applicationtestflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwLG3EDrSg9y-oSLzuWK-K5Ae2zfSf-Gc',
    appId: '1:455848600257:web:35d257b5e6c6c0f8676a40',
    messagingSenderId: '455848600257',
    projectId: 'applicationtestflutter',
    authDomain: 'applicationtestflutter.firebaseapp.com',
    storageBucket: 'applicationtestflutter.firebasestorage.app',
  );
}
